version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/school_schedule
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=school_schedule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # test:
  #   build: .
  #   command: pytest
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/school_schedule_test
  #   depends_on:
  #     - db

volumes:
  postgres_data: 